### ISSUE TITLE
Missing .a files trying to build the binary (Xcode 11.3.1)

### ISSUE THREAD

**Issue by scrutinizer11** [sqlcipher/openssl-xcode#17]
Building the project as per the instructions provided throws out two errors:

>ranlib: can't open file: /Users/home/Library/Developer/Xcode/DerivedData/openssl-cmnawkvroygzlpevqsgyzntmzqbz/Build/Products/Debug/libcrypto.a (No such file or directory)

>ranlib: can't open file: /Users/home/Library/Developer/Xcode/DerivedData/openssl-cmnawkvroygzlpevqsgyzntmzqbz/Build/Products/Debug/libssl.a (No such file or directory)

Examining the referred location reveals there's no both the **libcrypto.a** and **libssl.a** files. The source code folder contains identically named files but with the **num** extension.

Is there a solution?

**Comment by billymeltdown** [comment]
Hello @scrutinizer11, I'm not sure what the problem is here or how to fix it. Originally created as a build dependency for a `sqlcipher.xcodeproj` that is no longer available (as it is not needed), this project is also no longer needed to build SQLCipher from source and include it in Xcode projects (as we no longer need OpenSSL for the crypto provider on Apple platforms, we instead use Common Crypto). As such, we haven't updated this project in a very long time. It's no longer being maintained, and I've just added [a note](https://github.com/sqlcipher/openssl-xcode/blob/master/README.markdown#discontinued) to the README file to make that clear. Sorry to waste your time. 

I'm unsure where to point you next, as I don't know what your requirements are, but [we have a tutorial here](https://www.zetetic.net/sqlcipher/ios-tutorial/) for building SQLCipher and including it in iOS and macOS projects.
